from django.urls import path
from .views import (
    RegisterAPIView,
    UserProfileAPIView,
    ChangePasswordAPIView,
    ExcluirContaAPIView,
    PasswordResetRequestAPIView,
    PasswordResetConfirmAPIView,
    AceitarTermosAPIView,
    CookieTokenObtainPairAPIView,
    CookieTokenRefreshAPIView,
    MobileRegisterAPIView,
    MobileTokenObtainPairAPIView,
    MobileTokenRefreshAPIView,
    MobileLogoutAPIView,
    CsrfTokenAPIView,
    LogoutAPIView,
    GovernancaLegalAPIView,
    SessoesDispositivoAPIView,
    AutenticacaoDoisFatoresAPIView,
    PreferenciasNotificacaoAPIView,
    ExportarDadosAPIView,
)

urlpatterns = [
    path('csrf/', CsrfTokenAPIView.as_view(), name='csrf_token'),
    path('governanca/', GovernancaLegalAPIView.as_view(), name='governanca_legal'),
    path('login/', CookieTokenObtainPairAPIView.as_view(), name='token_obtain_pair'),
    path('mobile-login/', MobileTokenObtainPairAPIView.as_view(), name='mobile_token_obtain_pair'),
    path('mobile-refresh/', MobileTokenRefreshAPIView.as_view(), name='mobile_token_refresh'),
    path('mobile-logout/', MobileLogoutAPIView.as_view(), name='mobile_logout'),
    path('refresh/', CookieTokenRefreshAPIView.as_view(), name='token_refresh'),
    path('logout/', LogoutAPIView.as_view(), name='api_logout'),
    path('register/', RegisterAPIView.as_view(), name='api_register'),
    path('mobile-register/', MobileRegisterAPIView.as_view(), name='api_mobile_register'),
    path('profile/', UserProfileAPIView.as_view(), name='api_profile'),
    path('alterar-senha/', ChangePasswordAPIView.as_view(), name='api_alterar_senha'),
    path('recuperar-senha/', PasswordResetRequestAPIView.as_view(), name='api_recuperar_senha'),
    path('redefinir-senha/', PasswordResetConfirmAPIView.as_view(), name='api_redefinir_senha'),
    path('aceitar-termos/', AceitarTermosAPIView.as_view(), name='api_aceitar_termos'),
    path('excluir-conta/', ExcluirContaAPIView.as_view(), name='api_excluir_conta'),
    path('sessoes/', SessoesDispositivoAPIView.as_view(), name='api_sessoes'),
    path('dois-fatores/', AutenticacaoDoisFatoresAPIView.as_view(), name='api_dois_fatores'),
    path('preferencias-notificacao/', PreferenciasNotificacaoAPIView.as_view(), name='api_preferencias_notificacao'),
    path('exportar-dados/', ExportarDadosAPIView.as_view(), name='api_exportar_dados'),
]
