# Generated by Django 5.2.16 on 2026-07-14 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criada_por_sistema', models.BooleanField(default=False)),
                ('em_manutencao', models.BooleanField(default=False)),
                ('max_participantes', models.IntegerField(default=200)),
                ('total_denuncias', models.IntegerField(default=0)),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunidades_criadas', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(blank=True, related_name='comunidades_inscritas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DenunciaComunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('data_denuncia', models.DateTimeField(auto_now_add=True)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_registradas', to='comunidades.comunidade')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'denuncias_comunidades',
            },
        ),
        migrations.CreateModel(
            name='PostagemComunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='comunidades/posts/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='comunidades.comunidade')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
