# Generated by Django 6.0.8 on 2026-08-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denunciacomunidade',
            name='data_analise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denunciacomunidade',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('acolhida', 'Acolhida'), ('arquivada', 'Arquivada')], db_index=True, default='pendente', max_length=20),
        ),
    ]
