# Generated by Django 5.2.15 on 2026-07-06 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0002_postagemcomunidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='comunidades_inscritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
