# Generated by Django 6.0.7 on 2026-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0003_comunidade_membros'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='criada_por_sistema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='em_manutencao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='max_participantes',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='total_denuncias',
            field=models.IntegerField(default=0),
        ),
    ]
