# Generated by Django 6.0.8 on 2026-10-05 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0004_comunidade_chave_demonstrativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postagemcomunidade',
            name='retirada_privacidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respostapostagem',
            name='retirada_privacidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postagemcomunidade',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respostapostagem',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_comunidade', to=settings.AUTH_USER_MODEL),
        ),
    ]
