# Generated by Django 6.0.8 on 2026-10-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0005_postagemcomunidade_retirada_privacidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='retirada_privacidade',
            field=models.BooleanField(default=False),
        ),
    ]
