# Generated by Django 6.0.8 on 2026-10-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0006_comunidade_retirada_privacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='removida_definitivamente_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
