# Generated by Django 5.2.16 on 2026-07-14 21:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem Título', max_length=255, verbose_name='Título')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor')),
                ('ano_publicacao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de Publicação')),
                ('avaliacao', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Avaliação Média')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN')),
                ('paginas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Páginas')),
                ('edicao', models.CharField(blank=True, help_text='Ex: 1ª Edição, Traduzido por...', max_length=100, null=True, verbose_name='Edição')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Imagem de Capa')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='livros/', verbose_name='Arquivo PDF')),
                ('origem', models.CharField(choices=[('dominio_publico', 'Domínio Público'), ('autor_independente', 'Autor Independente')], default='dominio_publico', max_length=25, verbose_name='Origem da Obra')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('publicado', 'Publicado'), ('rejeitado', 'Rejeitado')], default='publicado', max_length=20, verbose_name='Status de Publicação')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='biblioteca.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'livros',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=150, verbose_name='Motivo')),
                ('data_denuncia', models.DateTimeField(auto_now_add=True, verbose_name='Data da Denúncia')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analisado', 'Analisado'), ('removido', 'Obra Removida')], default='pendente', max_length=20, verbose_name='Status da Denúncia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Denunciante')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='biblioteca.livro', verbose_name='Livro Denunciado')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'db_table': 'denuncias',
                'ordering': ['-data_denuncia'],
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('lendo', 'Lendo'), ('lido', 'Lido'), ('quero_ler', 'Quero ler')], default='quero_ler', max_length=20, verbose_name='Status de Leitura')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota do Leitor')),
                ('resenha', models.TextField(blank=True, null=True, verbose_name='Resenha/Avaliação')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_biblioteca', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_interagiram', to='biblioteca.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Item de Biblioteca',
                'verbose_name_plural': 'Itens de Biblioteca',
                'ordering': ['-data_adicao'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto de Perfil')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('status', models.CharField(choices=[('perfil_pendente', 'Pendente'), ('perfil_aprovado', 'Aprovado'), ('perfil_rejeitado', 'Rejeitado')], default='perfil_pendente', max_length=20, verbose_name='Status do Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_da_biblioteca', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Autenticação')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('observacao_admin', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_publicacao', to='biblioteca.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_publicacao', to=settings.AUTH_USER_MODEL, verbose_name='Autor Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Publicação',
                'verbose_name_plural': 'Solicitações de Publicação',
                'db_table': 'solicitacoes_publicacao',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['titulo'], name='livro_titulo_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['status'], name='livro_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='biblioteca',
            constraint=models.UniqueConstraint(fields=('user', 'livro'), name='unique_user_livro_estante'),
        ),
    ]
