# Generated by Django 6.0.6 on 2026-06-24 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='Id_Categorias', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome_Categoria', max_length=45)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(db_column='Id_Livros', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('autor', models.CharField(db_column='Autor', max_length=45)),
                ('data_publicacao', models.CharField(db_column='Data_Publicacao', max_length=45)),
                ('genero', models.CharField(db_column='Genero', max_length=45)),
                ('avaliacao', models.CharField(db_column='Avaliacao', max_length=45)),
                ('isbn', models.CharField(db_column='ISBN', max_length=45)),
                ('capa', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.CharField(blank=True, db_column='Caminho_PDF', max_length=255, null=True)),
                ('categoria', models.ForeignKey(db_column='Categorias_Id_Categorias', on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.categoria')),
            ],
            options={
                'db_table': 'livros',
            },
        ),
        migrations.CreateModel(
            name='ObraAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='obras/')),
                ('autor', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria')),
            ],
            options={
                'db_table': 'obras_autores',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('lendo', 'Lendo'), ('lido', 'Lido'), ('quero_ler', 'Quero ler')], default='quero_ler', max_length=20)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
            ],
            options={
                'unique_together': {('user', 'livro')},
            },
        ),
    ]
