# Generated by Django 5.2.16 on 2026-07-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='arquivada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='data_arquivamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='data_remocao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Remoção'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('publicado', 'Publicado'), ('rejeitado', 'Rejeitado'), ('removido', 'Removido na Lixeira')], default='publicado', max_length=20, verbose_name='Status de Publicação'),
        ),
    ]
