# Generated by Django 5.2.15 on 2026-07-13 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor_nome',
        ),
    ]
