# Generated by Django 6.0.7 on 2026-07-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_denuncia_arquivada_denuncia_data_arquivamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='xp_ganho_adicao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='xp_ganho_avaliacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='xp_ganho_favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='xp_ganho_leitura',
            field=models.BooleanField(default=False),
        ),
    ]
