# Generated by Django 5.2.15 on 2026-07-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_livro_autor_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaopublicacao',
            name='data_analise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaopublicacao',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitacaopublicacao',
            name='livro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_publicacao', to='biblioteca.livro', verbose_name='Livro'),
        ),
        migrations.AlterField(
            model_name='solicitacaopublicacao',
            name='observacao_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaopublicacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacaopublicacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_publicacao', to=settings.AUTH_USER_MODEL, verbose_name='Autor Solicitante'),
        ),
        migrations.DeleteModel(
            name='ObraAutor',
        ),
    ]
