# Generated by Django 6.0.6 on 2026-07-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
