# Generated by Django 6.0.6 on 2026-06-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_livro_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'managed': True},
        ),
    ]
