# Generated by Django 6.0.7 on 2026-07-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_biblioteca_xp_ganho_adicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='xp_ganho_resenha',
            field=models.BooleanField(default=False),
        ),
    ]
