# Generated by Django 6.0.6 on 2026-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_livro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
