# Generated by Django 5.2.16 on 2026-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_biblioteca_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraautor',
            name='aceitou_termos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obraautor',
            name='cpf_autor',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='obraautor',
            name='declaracao_autoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obraautor',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='obraautor',
            name='registro_autoral',
            field=models.CharField(blank=True, help_text='Número do registro na Biblioteca Nacional ou outro órgão.', max_length=100),
        ),
    ]
