# Generated by Django 6.0.8 on 2026-08-13 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_biblioteca_xp_ganho_resenha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracaoAutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_digest', models.CharField(max_length=64)),
                ('cpf_final', models.CharField(max_length=4)),
                ('registro_autoral', models.CharField(blank=True, max_length=100)),
                ('numero_registro', models.CharField(blank=True, max_length=20)),
                ('versao_termos', models.CharField(max_length=30)),
                ('declarado_em', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaracao', to='biblioteca.solicitacaopublicacao')),
            ],
            options={
                'db_table': 'declaracoes_autoria',
            },
        ),
    ]
