# Generated by Django 5.2.15 on 2026-06-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_livro_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'managed': False},
        ),
    ]
