# Generated by Django 5.2.16 on 2026-07-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_obraautor_aceitou_termos_obraautor_cpf_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='edicao',
            field=models.CharField(blank=True, help_text='Ex: 1ª Edição, Traduzido por...', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
