# Generated by Django 6.0.8 on 2026-08-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_declaracaoautoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conclusão da leitura'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='pagina_atual',
            field=models.PositiveIntegerField(default=0, verbose_name='Página atual'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='ultima_leitura_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última leitura'),
        ),
    ]
