# Generated by Django 6.0.6 on 2026-06-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_livro_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'managed': False},
        ),
    ]
