# Generated by Django 5.2.15 on 2026-06-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_livro_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livro',
            table='Livros',
        ),
    ]
