# Generated by Django 5.2.15 on 2026-06-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_alter_livro_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livro',
            table='livros',
        ),
    ]
