# Generated by Django 5.2.16 on 2026-07-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='resenha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
