# Generated by Django 6.0.8 on 2026-09-05 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def preencher_protocolos(apps, schema_editor):
    Denuncia = apps.get_model('biblioteca', 'Denuncia')
    for denuncia in Denuncia.objects.using(schema_editor.connection.alias).all().iterator():
        denuncia.protocolo = uuid.uuid4()
        denuncia.save(update_fields=['protocolo'])


def preservar_tentativas(apps, schema_editor):
    Solicitacao = apps.get_model('biblioteca', 'SolicitacaoPublicacao')
    Tentativa = apps.get_model('biblioteca', 'TentativaPublicacao')
    alias = schema_editor.connection.alias
    for solicitacao in Solicitacao.objects.using(alias).select_related('livro').iterator():
        livro = solicitacao.livro
        tentativa = Tentativa.objects.using(alias).create(
            solicitacao_id=solicitacao.pk, status=solicitacao.status,
            dados={campo: getattr(livro, campo) for campo in (
                'titulo', 'categoria_id', 'paginas', 'ano_publicacao', 'isbn', 'edicao',
            )}, pdf=livro.pdf.name or '', capa=livro.capa.name or '',
            analisada_em=solicitacao.data_analise, motivo=solicitacao.observacao_admin or '',
        )
        Tentativa.objects.using(alias).filter(pk=tentativa.pk).update(criada_em=solicitacao.data_envio)


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_acervo_alternativa_b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='decisao',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='evidencias',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='protocolo',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(preencher_protocolos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='denuncia', name='protocolo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='suspensao_cautelar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='retirado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('publicado', 'Publicado'), ('rejeitado', 'Rejeitado'), ('removido', 'Removido na Lixeira'), ('suspenso', 'Suspenso cautelarmente'), ('retirado', 'Retirado pelo autor')], default='publicado', max_length=20, verbose_name='Status de Publicação'),
        ),
        migrations.CreateModel(
            name='BloqueioPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novas_obras_apos', models.DateTimeField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventoPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('acao', models.CharField(max_length=60)),
                ('anterior', models.CharField(max_length=20)),
                ('posterior', models.CharField(max_length=20)),
                ('motivo', models.TextField(blank=True, max_length=2000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('denuncia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.denuncia')),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_publicacao', to='biblioteca.livro')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RecursoPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundamento', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('acolhido', 'Acolhido'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('decisao', models.TextField(blank=True, max_length=2000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recurso', to='biblioteca.eventopublicacao')),
            ],
        ),
        migrations.CreateModel(
            name='TentativaPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('dados', models.JSONField(default=dict)),
                ('pdf', models.FileField(blank=True, upload_to='livros/revisoes/')),
                ('capa', models.ImageField(blank=True, upload_to='capas/revisoes/')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('analisada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, max_length=2000)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='biblioteca.solicitacaopublicacao')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pendente')), fields=('solicitacao',), name='uma_tentativa_pendente')],
            },
        ),
        migrations.RunPython(preservar_tentativas, migrations.RunPython.noop),
    ]
