# Generated by Django 6.0.8 on 2026-10-05 22:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_alter_solicitacaopublicacao_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacaoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('quarentena', 'Quarentena'), ('verificando', 'Verificando'), ('limpo', 'Limpo'), ('rejeitado', 'Rejeitado'), ('erro', 'Erro de verificação')], default='quarentena', max_length=12)),
                ('tentativa', models.UUIDField(default=uuid.uuid4)),
                ('motor_versao', models.CharField(blank=True, max_length=160)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'biblioteca_verificacoes_arquivos',
            },
        ),
    ]
