# Generated by Django 6.0.8 on 2026-10-05 22:34

import biblioteca.caminhos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_verificacaoarquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=biblioteca.caminhos.pdf_livro, verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='pdf_amostra',
            field=models.FileField(blank=True, null=True, upload_to=biblioteca.caminhos.pdf_amostra, verbose_name='PDF da amostra'),
        ),
        migrations.AlterField(
            model_name='tentativapublicacao',
            name='pdf',
            field=models.FileField(blank=True, upload_to=biblioteca.caminhos.pdf_revisao),
        ),
    ]
