# Generated by Django 6.0.8 on 2026-10-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0016_alter_livro_pdf_alter_livro_pdf_amostra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='removido_definitivamente_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
