# Generated by Django 6.0.8 on 2026-10-07 21:56

import biblioteca.caminhos
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0017_livro_removido_definitivamente_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativapublicacao',
            name='pdf_amostra',
            field=models.FileField(blank=True, upload_to=biblioteca.caminhos.pdf_revisao),
        ),
        migrations.AddField(
            model_name='verificacaoarquivo',
            name='assinaturas_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='verificacaoarquivo',
            name='valido_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificacaoarquivo',
            name='verificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('publicado', 'Publicado'), ('rejeitado', 'Rejeitado'), ('removido', 'Removido na Lixeira'), ('suspenso', 'Suspenso cautelarmente'), ('retirado', 'Retirado pelo autor'), ('manutencao', 'Em manutenção de direitos'), ('expirado', 'Direitos expirados')], default='publicado', max_length=20, verbose_name='Status de Publicação'),
        ),
        migrations.CreateModel(
            name='LicencaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origem', models.CharField(choices=[('dominio_publico', 'Domínio Público'), ('autor_independente', 'Autor Independente'), ('licenciado', 'Acervo Licenciado')], max_length=25)),
                ('edicao_sha256', models.CharField(max_length=64)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('amostra_sha256', models.CharField(blank=True, max_length=64)),
                ('referencia_cofre', models.UUIDField(unique=True)),
                ('recibo_sha256', models.CharField(max_length=64, unique=True)),
                ('chave_id', models.CharField(max_length=60)),
                ('versao', models.CharField(max_length=30)),
                ('territorios', models.JSONField()),
                ('modelos_acesso', models.JSONField()),
                ('vigente_de', models.DateTimeField()),
                ('vigente_ate', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('conferida', 'Conferida'), ('revogada', 'Revogada'), ('disputa', 'Em disputa')], default='conferida', max_length=12)),
                ('conferida_em', models.DateTimeField(auto_now_add=True)),
                ('alterada_em', models.DateTimeField(auto_now=True)),
                ('conferida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencas', to='biblioteca.livro')),
            ],
            options={
                'permissions': [('conferir_direitos', 'Conferir e revogar direitos sem acesso a documentos')],
                'indexes': [models.Index(fields=['livro', 'edicao_sha256'], name='licenca_livro_edicao_idx')],
            },
        ),
    ]
