# Generated by Django 6.0.8 on 2026-10-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0019_direitos_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencaobra',
            name='chave_publica_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
