# Generated by Django 6.0.8 on 2026-08-20 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_flags_iniciais(apps, schema_editor):
    FeatureFlag = apps.get_model('dashboard', 'FeatureFlag')
    FeatureFlag.objects.bulk_create([
        FeatureFlag(
            chave='perfil_jornada_leitura',
            descricao='Exibe meta anual e progresso de leitura no perfil.',
            habilitada=True,
        ),
        FeatureFlag(
            chave='moderacao_no_perfil',
            descricao='Permite decisões rápidas na aba de moderação do perfil administrativo.',
            habilitada=True,
        ),
        FeatureFlag(
            chave='autenticacao_2fa',
            descricao='Disponibiliza verificação em duas etapas por aplicativo autenticador.',
            habilitada=True,
        ),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.SlugField(max_length=80, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('habilitada', models.BooleanField(default=False)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('atualizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flags_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ['chave'],
            },
        ),
        migrations.RunPython(criar_flags_iniciais, migrations.RunPython.noop),
    ]
