import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../navigation/types';
import { featureService, NotificationItem } from '../services/featureService';
import { colors } from '../theme/colors';

type Props=NativeStackScreenProps<RootStackParamList,'Notifications'>;
export const NotificationsScreen=({navigation}:Props)=>{const [items,setItems]=useState<NotificationItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setItems(await featureService.getNotifications());}catch{setError('Nao foi possivel carregar as notificacoes.');}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);const markRead=async(item:NotificationItem)=>{if(item.read)return;setItems(current=>current.map(value=>value.id===item.id?{...value,read:true}:value));try{await featureService.markNotificationRead(item.id);}catch{setItems(current=>current.map(value=>value.id===item.id?{...value,read:false}:value));}};const markAll=async()=>{const previous=items;setItems(current=>current.map(value=>({...value,read:true})));try{await featureService.markAllNotificationsRead();}catch{setItems(previous);}};return <SafeAreaView style={styles.container}><View style={styles.header}><TouchableOpacity style={styles.icon} onPress={()=>navigation.goBack()}><Ionicons name="arrow-back" size={23} color={colors.textPrimary}/></TouchableOpacity><Text style={styles.title}>Notificacoes</Text><TouchableOpacity style={styles.icon} onPress={()=>void markAll()}><Ionicons name="checkmark-done" size={22} color={colors.primary}/></TouchableOpacity></View>{loading?<View style={styles.center}><ActivityIndicator size="large" color={colors.primary}/></View>:error?<View style={styles.center}><Text style={styles.state}>{error}</Text><TouchableOpacity style={styles.retry} onPress={load}><Text style={styles.retryText}>Tentar novamente</Text></TouchableOpacity></View>:<FlatList data={items} keyExtractor={item=>String(item.id)} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.center}><Ionicons name="notifications-off-outline" size={44} color={colors.textMuted}/><Text style={styles.state}>Voce nao possui notificacoes.</Text></View>} renderItem={({item})=><TouchableOpacity style={[styles.card,!item.read&&styles.unread]} onPress={()=>void markRead(item)}><View style={styles.badge}><Ionicons name={item.read?'mail-open-outline':'mail-outline'} size={20} color={colors.primary}/></View><View style={styles.info}><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.message}>{item.message}</Text>{item.createdAt&&<Text style={styles.date}>{new Date(item.createdAt).toLocaleDateString('pt-BR')}</Text>}</View>{!item.read&&<View style={styles.dot}/>}</TouchableOpacity>}/>}</SafeAreaView>};
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},header:{flexDirection:'row',alignItems:'center',padding:14,borderBottomWidth:1,borderBottomColor:colors.border},icon:{width:42,height:42,alignItems:'center',justifyContent:'center'},title:{flex:1,textAlign:'center',color:colors.textPrimary,fontSize:18,fontWeight:'700'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:28},state:{color:colors.textSecondary,textAlign:'center',marginTop:12},retry:{marginTop:16,padding:13,backgroundColor:colors.primary,borderRadius:22},retryText:{color:colors.textPrimary,fontWeight:'700'},list:{padding:18,flexGrow:1},card:{flexDirection:'row',alignItems:'center',padding:14,marginBottom:9,borderRadius:12,backgroundColor:colors.cardBackground,borderWidth:1,borderColor:colors.border,opacity:.75},unread:{opacity:1,borderColor:colors.primary},badge:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},info:{flex:1,marginLeft:12},itemTitle:{color:colors.textPrimary,fontSize:15,fontWeight:'700'},message:{color:colors.textSecondary,fontSize:13,lineHeight:18,marginTop:4},date:{color:colors.textMuted,fontSize:11,marginTop:6},dot:{width:8,height:8,borderRadius:4,backgroundColor:colors.primary,marginLeft:8}});
