import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Image, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../navigation/types';
import { authService, FullUserProfile } from '../services/authService';
import { colors } from '../theme/colors';

type Props = NativeStackScreenProps<RootStackParamList, 'PublicProfile'>;
export const PublicProfileScreen = ({ route, navigation }: Props) => {
  const [profile,setProfile]=useState<FullUserProfile|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setProfile(await authService.getFullUserProfile(route.params.username));}catch{setError('Este perfil nao esta disponivel.');}finally{setLoading(false);}},[route.params.username]);
  useEffect(()=>{void load();},[load]);
  return <SafeAreaView style={styles.container}><View style={styles.header}><TouchableOpacity style={styles.icon} onPress={()=>navigation.goBack()}><Ionicons name="arrow-back" size={23} color={colors.textPrimary}/></TouchableOpacity><Text style={styles.headerTitle}>Perfil publico</Text><View style={styles.icon}/></View>{loading?<View style={styles.center}><ActivityIndicator size="large" color={colors.primary}/></View>:error||!profile?<View style={styles.center}><Text style={styles.state}>{error}</Text><TouchableOpacity style={styles.retry} onPress={load}><Text style={styles.retryText}>Tentar novamente</Text></TouchableOpacity></View>:<ScrollView contentContainerStyle={styles.content}>{profile.perfil.foto?<Image source={{uri:profile.perfil.foto}} style={styles.avatar}/>:<View style={styles.avatar}><Ionicons name="person" size={40} color={colors.primary}/></View>}<Text style={styles.name}>{profile.usuario.nome}</Text><Text style={styles.username}>@{profile.usuario.username}</Text><Text style={styles.bio}>{profile.perfil.bio||profile.perfil.descricao_perfil||'Sem biografia.'}</Text><View style={styles.stats}>{[['Lidos',profile.estatisticas.total_lidos],['Lendo',profile.estatisticas.lendo_agora],['Comunidades',profile.estatisticas.total_comunidades]].map(([label,value])=><View style={styles.stat} key={String(label)}><Text style={styles.statNumber}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>)}</View><Text style={styles.section}>Livros favoritos</Text>{profile.favoritos.livros.length===0?<Text style={styles.state}>Nenhum favorito publico.</Text>:profile.favoritos.livros.map(book=><TouchableOpacity key={book.id} style={styles.book} onPress={()=>navigation.navigate('BookDetail',{bookId:String(book.id),title:book.titulo})}>{book.capa?<Image source={{uri:book.capa}} style={styles.cover}/>:<View style={styles.cover}><Ionicons name="book" size={21} color={colors.primary}/></View>}<View style={{flex:1}}><Text style={styles.bookTitle}>{book.titulo}</Text><Text style={styles.bookAuthor}>{book.autor}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.textMuted}/></TouchableOpacity>)}</ScrollView>}</SafeAreaView>;
};
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},header:{flexDirection:'row',alignItems:'center',padding:14,borderBottomWidth:1,borderBottomColor:colors.border},icon:{width:42,height:42,alignItems:'center',justifyContent:'center'},headerTitle:{flex:1,textAlign:'center',color:colors.textPrimary,fontSize:18,fontWeight:'700'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:28},content:{padding:20,alignItems:'center',paddingBottom:40},avatar:{width:86,height:86,borderRadius:43,alignItems:'center',justifyContent:'center',backgroundColor:colors.cardBackground},name:{color:colors.textPrimary,fontSize:22,fontWeight:'700',marginTop:13},username:{color:colors.primary,fontSize:13,marginTop:3},bio:{color:colors.textSecondary,fontSize:14,lineHeight:21,textAlign:'center',marginTop:14},stats:{alignSelf:'stretch',flexDirection:'row',marginTop:20,paddingVertical:16,borderRadius:12,backgroundColor:colors.cardBackground,borderWidth:1,borderColor:colors.border},stat:{flex:1,alignItems:'center'},statNumber:{color:colors.textPrimary,fontSize:18,fontWeight:'700'},statLabel:{color:colors.textMuted,fontSize:11,marginTop:3},section:{alignSelf:'stretch',color:colors.textPrimary,fontSize:17,fontWeight:'700',marginTop:26,marginBottom:11},state:{color:colors.textSecondary,textAlign:'center',marginTop:12},retry:{marginTop:16,padding:14,backgroundColor:colors.primary,borderRadius:22},retryText:{color:colors.textPrimary,fontWeight:'700'},book:{alignSelf:'stretch',flexDirection:'row',alignItems:'center',padding:11,marginBottom:8,borderRadius:10,backgroundColor:colors.cardBackground},cover:{width:40,height:54,borderRadius:6,alignItems:'center',justifyContent:'center',backgroundColor:colors.background,marginRight:11},bookTitle:{color:colors.textPrimary,fontSize:14,fontWeight:'700'},bookAuthor:{color:colors.textMuted,fontSize:12,marginTop:3}});
