# Generated by Django 5.2.16 on 2026-07-14 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico', models.CharField(blank=True, max_length=45, null=True)),
                ('descricao_perfil', models.CharField(blank=True, max_length=45, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avatares/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil_privado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
