# Generated by Django 6.0.6 on 2026-06-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico', models.CharField(blank=True, max_length=45, null=True)),
                ('descricao_perfil', models.CharField(blank=True, max_length=45, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
