# Generated by Django 6.0.8 on 2026-08-20 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_perfil/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='meta_leitura_anual',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
