# Generated by Django 6.0.7 on 2026-07-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_remove_perfil_username_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='perfil_privado',
            field=models.BooleanField(default=False),
        ),
    ]
