# Generated by Django 6.0.8 on 2026-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0009_privacidade_aniversario_sem_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='exibir_data_nascimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='exibir_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='exibir_idade',
            field=models.BooleanField(default=False),
        ),
    ]
