# Generated by Django 5.2.15 on 2026-07-28 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='notificacao',
            name='link_destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('ASSINATURA', 'Assinatura & Pagamentos'), ('LIVRO', 'Novidades e Leitura'), ('SISTEMA', 'Avisos do Sistema')], default='SISTEMA', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['usuario', 'lida'], name='notificacoe_usuario_56e4b8_idx'),
        ),
    ]
