# Generated by Django 6.0.6 on 2026-06-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificacao_autor',
            field=models.BooleanField(default=False),
        ),
    ]
