# Generated by Django 6.0.6 on 2026-06-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('leitor', 'Leitor'), ('autor', 'Autor Independente')], default='leitor', max_length=20),
        ),
    ]
