# Generated by Django 6.0.8 on 2026-08-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_notificacao_options_notificacao_link_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('leitor', 'Leitor'), ('aguardando_aprovacao', 'Aguardando Aprovação de Autor'), ('autor', 'Autor Independente'), ('admin', 'Administrador')], default='leitor', max_length=20),
        ),
    ]
