# Generated by Django 5.2.15 on 2026-07-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_remove_perfil_username_perfil_usuario'),
        ('usuarios', '0002_usuario_notificacao_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='perfis.perfil'),
        ),
    ]
