# Generated by Django 6.0.7 on 2026-07-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_aceite_termos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='termos_aceitos',
            field=models.BooleanField(default=False),
        ),
    ]
