# Generated by Django 5.2.16 on 2026-07-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
