# Generated by Django 6.0.8 on 2026-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_versao_termos_aceita'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='onboarding_lembretes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
