# Generated by Django 6.0.8 on 2026-08-20 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_onboarding_lembretes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificacoes_assinaturas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificacoes_comunidades',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificacoes_email',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AutenticacaoDoisFatores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segredo_criptografado', models.TextField()),
                ('habilitada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autenticacao_2fa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'autenticacao_dois_fatores',
            },
        ),
        migrations.CreateModel(
            name='SessaoDispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_jti', models.CharField(max_length=255, unique=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade_em', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField()),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_dispositivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessoes_dispositivo',
                'ordering': ['-ultima_atividade_em'],
                'indexes': [models.Index(fields=['usuario', 'revogada_em'], name='sessoes_dis_usuario_4551a9_idx')],
            },
        ),
    ]
