# Generated by Django 6.0.8 on 2026-09-08 20:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def promover_admins_operacionais_a_moderadores(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    Evento = apps.get_model('usuarios', 'EventoGovernancaConta')
    alias = schema_editor.connection.alias
    afetados = list(Usuario.objects.using(alias).filter(
        tipo='admin',
        user_auth__is_superuser=False,
    ).values_list('user_auth_id', flat=True))
    Usuario.objects.using(alias).filter(user_auth_id__in=afetados).update(tipo='moderador')
    for usuario_id in afetados:
        Evento.objects.using(alias).create(
            usuario_id=usuario_id,
            ator_id=None,
            tipo='papel_alterado',
            motivo='Conversão de administrador operacional legado para moderador.',
            metadados={
                'migracao': 'usuarios.0008.admin_para_moderador',
                'papel_anterior': 'admin',
                'papel_novo': 'moderador',
            },
        )


def restaurar_moderadores_como_admins(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    Evento = apps.get_model('usuarios', 'EventoGovernancaConta')
    alias = schema_editor.connection.alias
    eventos = Evento.objects.using(alias).filter(
        metadados__migracao='usuarios.0008.admin_para_moderador',
    )
    ids_convertidos = list(eventos.values_list('usuario_id', flat=True))
    Usuario.objects.using(alias).filter(
        user_auth_id__in=ids_convertidos,
        tipo='moderador',
    ).update(tipo='admin')
    eventos.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_notificacoes_assinaturas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('leitor', 'Leitor'), ('aguardando_aprovacao', 'Aguardando Aprovação de Autor'), ('autor', 'Autor Independente'), ('moderador', 'Moderador'), ('admin', 'Administrador')], default='leitor', max_length=20),
        ),
        migrations.CreateModel(
            name='EventoGovernancaConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('suspensao_aplicada', 'Suspensão aplicada'), ('suspensao_revogada', 'Suspensão revogada'), ('suspensao_expirada', 'Suspensão expirada'), ('papel_alterado', 'Papel alterado')], max_length=24)),
                ('motivo', models.TextField(max_length=2000)),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_governanca_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_governanca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_eventos_governanca_conta',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='conta', max_length=40)),
                ('assunto', models.CharField(max_length=120)),
                ('mensagem', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em análise'), ('respondida', 'Respondida'), ('encerrada', 'Encerrada')], default='aberta', max_length=16)),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('resposta', models.TextField(blank=True, max_length=4000)),
                ('criada_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_suporte_atendidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_suporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_solicitacoes_suporte',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='SuspensaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_dias', models.PositiveSmallIntegerField(choices=[(3, '3 dias'), (7, '7 dias'), (15, '15 dias'), (30, '30 dias')])),
                ('categoria', models.CharField(max_length=40)),
                ('justificativa', models.TextField(max_length=2000)),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('revogada', 'Revogada'), ('expirada', 'Expirada')], default='ativa', max_length=12)),
                ('inicia_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('termina_em', models.DateTimeField(db_index=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
                ('aplicada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensoes_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('revogada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensoes_revogadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes_conta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_suspensoes_conta',
                'ordering': ['-criada_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ativa')), fields=('usuario',), name='usuarios_uma_suspensao_ativa')],
            },
        ),
        migrations.RunPython(
            promover_admins_operacionais_a_moderadores,
            restaurar_moderadores_como_admins,
        ),
    ]
