# Generated by Django 6.0.8 on 2026-10-05 18:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_estado_etario_conta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservacaoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('destino', models.CharField(max_length=24)),
                ('recurso', models.CharField(max_length=100)),
                ('recurso_ref', models.CharField(max_length=100)),
                ('motivo_codigo', models.CharField(max_length=40)),
                ('iniciada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('revisar_em', models.DateTimeField()),
                ('liberada_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='solicitacaosuporte',
            name='encerrada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaosuporte',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_suporte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EncerramentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conta_id_original', models.PositiveBigIntegerField()),
                ('conta_criada_em', models.DateTimeField()),
                ('encerrada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('descarte_ate', models.DateTimeField()),
                ('prova_ate', models.DateTimeField()),
                ('descartada_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encerramento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProvaPrivacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evento_ref', models.UUIDField(unique=True)),
                ('classe', models.CharField(choices=[('R09', 'Prova mínima'), ('R10', 'Declaração etária'), ('R13', 'Preservação seletiva')], max_length=3)),
                ('chave_id', models.CharField(max_length=40)),
                ('conteudo_cifrado', models.TextField()),
                ('registrada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('encerramento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provas', to='usuarios.encerramentoconta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provas_privacidade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DestinoDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('destino', models.CharField(max_length=24)),
                ('classe', models.CharField(max_length=3)),
                ('recurso', models.CharField(max_length=100)),
                ('recurso_ref', models.CharField(max_length=100)),
                ('objeto', models.TextField(blank=True)),
                ('evento_em', models.DateTimeField(null=True)),
                ('limite_em', models.DateTimeField(null=True)),
                ('estado', models.CharField(default='pendente', max_length=20)),
                ('motivo_codigo', models.CharField(blank=True, max_length=40)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('encerramento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='usuarios.encerramentoconta')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('encerramento', 'destino', 'recurso', 'recurso_ref'), name='descarte_destino_recurso_unico')],
            },
        ),
    ]
