# Generated by Django 6.0.8 on 2026-10-05 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_preservacaodados_solicitacaosuporte_encerrada_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provaprivacidade',
            name='recurso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='provaprivacidade',
            name='recurso_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventogovernancaconta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_governanca', to=settings.AUTH_USER_MODEL),
        ),
    ]
