# Generated by Django 6.0.8 on 2026-10-06 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_privacidade_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoetarioconta',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_etarios', to='usuarios.solicitacaosuporte'),
        ),
        migrations.AlterField(
            model_name='eventoetarioconta',
            name='tipo',
            field=models.CharField(choices=[('conta_inicializada', 'Conta inicializada'), ('declaracao_registrada', 'Declaração registrada'), ('correcao_registrada', 'Correção registrada'), ('mudanca_de_faixa', 'Mudança de faixa'), ('revisao_iniciada', 'Revisão iniciada'), ('revisao_solicitada', 'Revisão solicitada'), ('revisao_concluida', 'Revisão concluída')], max_length=28),
        ),
        migrations.CreateModel(
            name='RevisaoEtaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_solicitacao', models.UUIDField(unique=True)),
                ('decisao', models.CharField(blank=True, choices=[('confirmar_declaracao', 'Confirmar declaração atual'), ('orientar_correcao', 'Orientar correção pelo titular')], default='', max_length=24)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revisao_etaria', to='usuarios.solicitacaosuporte')),
            ],
        ),
    ]
