# Generated by Django 6.0.8 on 2026-10-07 00:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0017_livro_removido_definitivamente_em'),
        ('comunidades', '0007_comunidade_removida_definitivamente_em'),
        ('usuarios', '0013_eventoetarioconta_solicitacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpedimentoModeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(max_length=100)),
                ('recurso_id', models.PositiveBigIntegerField()),
                ('causa', models.CharField(choices=[('retencao', 'retencao'), ('incidente', 'incidente'), ('ordem_autoridade', 'ordem_autoridade'), ('preservacao', 'preservacao')], max_length=24)),
                ('referencia', models.CharField(max_length=200)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('liberada_em', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimiteModeracao',
            fields=[
                ('chave', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('janela', models.DateTimeField(db_index=True)),
                ('tentativas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioModeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('feriados', models.JSONField(default=list)),
                ('referencia', models.CharField(max_length=200)),
                ('conferido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('conferido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CasoModeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origem', models.CharField(choices=[('publica', 'publica'), ('obra', 'obra'), ('comunidade', 'comunidade'), ('suporte', 'suporte'), ('suspensao', 'suspensao'), ('recurso', 'recurso'), ('conselho', 'conselho')], max_length=16)),
                ('origem_id', models.PositiveBigIntegerField(null=True)),
                ('chave_entrada', models.UUIDField(null=True, unique=True)),
                ('acesso_digest', models.CharField(blank=True, max_length=64)),
                ('categoria', models.CharField(max_length=40)),
                ('dados_cifrados', models.TextField(blank=True)),
                ('chave_id', models.CharField(blank=True, max_length=40)),
                ('prioridade', models.CharField(blank=True, choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2')], max_length=2)),
                ('estado', models.CharField(choices=[('aguarda_triagem', 'Aguarda triagem'), ('em_analise', 'Em análise'), ('aguarda_complemento', 'Aguarda complemento'), ('decidido', 'Decidido'), ('encerrado', 'Encerrado')], db_index=True, default='aguarda_triagem', max_length=24)),
                ('recebido_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confirmado_em', models.DateTimeField(null=True)),
                ('triado_em', models.DateTimeField(null=True)),
                ('confirmacao_humana_ate', models.DateTimeField(null=True)),
                ('triagem_ate', models.DateTimeField(null=True)),
                ('decisao_ate', models.DateTimeField(null=True)),
                ('decidido_em', models.DateTimeField(null=True)),
                ('comunicado_em', models.DateTimeField(null=True)),
                ('encerrado_em', models.DateTimeField(null=True)),
                ('regra', models.CharField(blank=True, max_length=200)),
                ('evidencia_ref', models.CharField(blank=True, max_length=200)),
                ('medida', models.CharField(blank=True, max_length=32)),
                ('resposta_publica', models.TextField(blank=True, max_length=4000)),
                ('retorno_estado', models.CharField(choices=[('pendente', 'Pendente'), ('disponivel', 'Disponível no protocolo'), ('consultado', 'Consultado')], default='pendente', max_length=16)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alvo_comunidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_moderacao', to='comunidades.comunidade')),
                ('alvo_livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_moderacao', to='biblioteca.livro')),
                ('alvo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('calendario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.calendariomoderacao')),
                ('decisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_decididos', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_assumidos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_proprios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recebido_em', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventoModeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('acao', models.CharField(max_length=40)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('dados_cifrados', models.TextField(blank=True)),
                ('chave_id', models.CharField(blank=True, max_length=40)),
                ('ator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuarios.casomoderacao')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PedidoConselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('chave', models.UUIDField(unique=True)),
                ('acao', models.CharField(choices=[('remover', 'Remover definitivamente'), ('restaurar', 'Restaurar excepcionalmente')], max_length=16)),
                ('recurso', models.CharField(max_length=100)),
                ('recurso_id', models.PositiveBigIntegerField()),
                ('snapshot', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('executado', 'Executado'), ('cancelado', 'Cancelado')], default='pendente', max_length=12)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('executado_em', models.DateTimeField(null=True)),
                ('resultado_ref', models.CharField(blank=True, max_length=100)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_conselho', to='usuarios.casomoderacao')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AprovacaoConselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.CharField(max_length=64)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprovador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to='usuarios.pedidoconselho')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoModeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.UUIDField(unique=True)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('acolhido', 'Acolhido'), ('recusado', 'Recusado')], default='pendente', max_length=12)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('decidido_em', models.DateTimeField(null=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recurso_atendido', to='usuarios.casomoderacao')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recurso', to='usuarios.casomoderacao')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='calendariomoderacao',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gte', models.F('inicio'))), name='moderacao_calendario_intervalo'),
        ),
        migrations.AddConstraint(
            model_name='casomoderacao',
            constraint=models.UniqueConstraint(condition=models.Q(('origem_id__isnull', False)), fields=('origem', 'origem_id'), name='moderacao_origem_unica'),
        ),
        migrations.AddConstraint(
            model_name='pedidoconselho',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendente')), fields=('recurso', 'recurso_id'), name='conselho_um_pedido_pendente'),
        ),
        migrations.AddConstraint(
            model_name='aprovacaoconselho',
            constraint=models.UniqueConstraint(fields=('pedido', 'aprovador'), name='conselho_aprovador_distinto'),
        ),
    ]
