# Generated by Django 6.0.8 on 2026-10-07 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_moderacao_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='casomoderacao',
            name='suspensao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caso_moderacao', to='usuarios.suspensaoconta'),
        ),
    ]
