# Generated by Django 6.0.8 on 2026-10-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_casomoderacao_suspensao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casomoderacao',
            options={'ordering': ['recebido_em', 'pk'], 'permissions': [('operar_risco_grave', 'Operar P0/P1, suspensão e recursos de moderação')]},
        ),
    ]
