# Generated by Django 6.0.8 on 2026-08-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_assinatura_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoStripeProcessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eventos_stripe_processados',
            },
        ),
    ]
