# Generated by Django 5.2.15 on 2026-07-29 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único para checagem via código (ex: primeira_leitura_concluida)', unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(default='bi-award', help_text='Classe do ícone Bootstrap Icons (ex: bi-trophy, bi-star)', max_length=100)),
                ('categoria', models.CharField(choices=[('leitura', 'Leitura'), ('comunidade', 'Comunidade/Críticas'), ('assinatura', 'Assinatura'), ('especial', 'Especial')], default='leitura', max_length=20)),
                ('pontos_recompensa', models.PositiveIntegerField(default=50, help_text='XP concedido ao desbloquear')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
            },
        ),
        migrations.CreateModel(
            name='ProgressoLeitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_xp', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Pontos de Experiência (XP)')),
                ('nivel', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Nível')),
                ('dias_seguidos', models.PositiveIntegerField(default=0, verbose_name='Dias Seguidos de Leitura')),
                ('ultima_atividade', models.DateField(blank=True, null=True, verbose_name='Data da Última Atividade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_gamificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso do Leitor',
                'verbose_name_plural': 'Progressos dos Leitores',
            },
        ),
        migrations.CreateModel(
            name='ConquistaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_desbloqueio', models.DateTimeField(default=django.utils.timezone.now)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_conquistaram', to='gamificacao.conquista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do Usuário',
                'verbose_name_plural': 'Conquistas dos Usuários',
                'constraints': [models.UniqueConstraint(fields=('user', 'conquista'), name='unique_conquista_usuario')],
            },
        ),
    ]
