"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

import os
import warnings
from datetime import timedelta
from pathlib import Path
import dj_database_url
from decouple import config
from django.core.exceptions import ImproperlyConfigured
from django import VERSION as DJANGO_VERSION

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!

_development_secret = 'django-insecure-local-development-only-change-me'
SECRET_KEY = config('SECRET_KEY', default=_development_secret)

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = config('DEBUG', default=True, cast=bool)

if not DEBUG and SECRET_KEY == _development_secret:
    raise ImproperlyConfigured('SECRET_KEY é obrigatória quando DEBUG=False.')

# Decisão explícita da equipe em 13/08/2026: manter temporariamente o pin
# compartilhado Django 4.2 para compatibilidade. A série encerrou suporte de
# segurança em 07/04/2026 e deve ser atualizada antes do próximo go-live.
if DJANGO_VERSION < (5, 2):
    warnings.warn(
        'Django 4.2 está fora de suporte. Migração para 5.2 LTS ou superior está pendente.',
        RuntimeWarning,
        stacklevel=2,
    )

# Configuração de hosts permitidos

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,0.0.0.0,192.168.1.171,*",
).split(",")

if not DEBUG:
    if '*' in ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            'ALLOWED_HOSTS deve ser definido explicitamente em produção.'
        )
    ALLOWED_HOSTS += [
        ".onrender.com",
        "parabook-nl8o.onrender.com",
        ".railway.app",
    ]

# Configuração de origens confiáveis para CSRF

# Precisa da PORTA do Vite (5173): o Django 6 faz Origin check estrito
# (match exato de esquema://host:porta), então "http://localhost" não
# cobre "http://localhost:5173". Espelha o CORS_ALLOWED_ORIGINS abaixo —
# os dois estavam dessincronizados e era o que barrava POST do frontend
# de dev com 403 CSRF.
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:5173,http://127.0.0.1:5173,http://localhost,http://127.0.0.1",
).split(",")

if not DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "https://*.onrender.com",
        "https://parabook-nl8o.onrender.com",
        "https://*.railway.app",
    ]

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=3600, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool
    )
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'corsheaders',
    'usuarios',
    'perfis',
    'comunidades',
    'biblioteca',
    'dashboard',
    'django_extensions',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'assinaturas',
    'notificacoes',
    'gamificacao',
    'biblioteca.api.apps.ApiConfig',
]

MIDDLEWARE = [
    # Deve ficar antes de middlewares que podem responder antecipadamente
    # (SecurityMiddleware/WhiteNoise), inclusive para preflights OPTIONS.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarios.middleware.ForcarAceiteTermosMiddleware',
    'assinaturas.middleware.PremiumRequiredMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'assinaturas.context_processors.anuncios_context',
                'notificacoes.context_processors.notificacoes_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Configuração CORS

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default=(
        "http://localhost:5173,http://127.0.0.1:5173,"
        "http://localhost:8081,http://127.0.0.1:8081"
    ),
).split(",")

# Libera automaticamente qualquer subdomínio das plataformas de deploy
# (ex: o futuro Static Site do parabook-web no Render), sem precisar
# hardcodar a URL exata a cada novo serviço criado.

if not DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^https://.*\.onrender\.com$",
        r"^https://.*\.railway\.app$",
    ]

# DATABASE CONFIGURATION (PostgreSQL — unificado para todos os ambientes)

DATABASE_URL = config('DATABASE_URL', default=None)

if not DATABASE_URL:
    if not DEBUG:
        raise ImproperlyConfigured('DATABASE_URL é obrigatória quando DEBUG=False.')
    _db_name = config('DB_NAME', default='parabook_db')
    _db_user = config('DB_USER', default='parabook_user')
    _db_pass = config('DB_PASSWORD', default='parabook_password')
    _db_host = config('DB_HOST', default='localhost')
    _db_port = config('DB_PORT', default='5432')
    DATABASE_URL = (
        f"postgres://{_db_user}:{_db_pass}@{_db_host}:{_db_port}/{_db_name}"
    )

DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# DATABASES = {

# "default": {

# "ENGINE": "django.db.backends.mysql",

# "NAME": "mydb",

# "USER": "root",

# "PASSWORD": "admin",

# "HOST": "127.0.0.1",

# "PORT": "3306",

# "OPTIONS": {

# "charset": "utf8mb4",

# },

# }

# }

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'
    },
]

# Internationalization

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Belem'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Credenciais do Supabase obtidas via decouple/env

SUPABASE_URL = config("SUPABASE_URL", default=None)
SUPABASE_KEY = config("SUPABASE_KEY", default=None)
SUPABASE_STORAGE_BUCKET_NAME = "parabook-media"

# Define se o storage padrão de uploads será o Supabase ou o FileSystem local

if not DEBUG and SUPABASE_URL and SUPABASE_KEY:
    MEDIA_URL = (
        f"{SUPABASE_URL}/storage/v1/object/public/"
        f"{SUPABASE_STORAGE_BUCKET_NAME}/"
    )
else:
    MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuração consolidada dos Storages

STATICFILES_USE_MANIFEST = config(
    "STATICFILES_USE_MANIFEST",
    default=not DEBUG,
    cast=bool,
)

STORAGES = {
    "staticfiles": {
        # Em desenvolvimento os arquivos vêm diretamente dos finders. Em
        # produção, ou quando o CI pede explicitamente, collectstatic gera o
        # manifest comprimido do WhiteNoise.
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if STATICFILES_USE_MANIFEST
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        )
    },
    "default": {
        "BACKEND": (
            "storages.backends.supabase.SupabaseStorage"
            if (not DEBUG and SUPABASE_URL and SUPABASE_KEY)
            else "django.core.files.storage.FileSystemStorage"
        )
    },
}

WHITENOISE_MANIFEST_STRICT = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

MAX_BOOK_UPLOAD_SIZE = config('MAX_BOOK_UPLOAD_SIZE', default=5 * 1024 * 1024, cast=int)
MAX_BOOK_PAGES = config('MAX_BOOK_PAGES', default=5000, cast=int)
DATA_UPLOAD_MAX_MEMORY_SIZE = config(
    'DATA_UPLOAD_MAX_MEMORY_SIZE', default=6 * 1024 * 1024, cast=int
)
FILE_UPLOAD_MAX_MEMORY_SIZE = config(
    'FILE_UPLOAD_MAX_MEMORY_SIZE', default=5 * 1024 * 1024, cast=int
)
# A versão é parte da evidência de aceite. Alterá-la força novo aceite nos
# clientes web e legado; não reutilize uma versão para textos materialmente
# diferentes.
TERMS_VERSION = config('TERMS_VERSION', default='2026-08-13')

# Identificação pública do agente de tratamento. Os valores definitivos devem
# ser preenchidos no Render após definição da entidade responsável; não
# presumimos que SENAC, integrantes da equipe ou fornecedores sejam o
# controlador sem instrumento formal.
LEGAL_CONTROLLER_NAME = config(
    'LEGAL_CONTROLLER_NAME', default='ParaBook — projeto em validação'
)
LEGAL_CONTROLLER_DOCUMENT = config('LEGAL_CONTROLLER_DOCUMENT', default='')
LEGAL_CONTROLLER_ADDRESS = config('LEGAL_CONTROLLER_ADDRESS', default='')
LEGAL_PRIVACY_CONTACT = config('LEGAL_PRIVACY_CONTACT', default='')
LEGAL_JURISDICTION = 'Brasil'

# Configuração de e-mail:
# Em desenvolvimento local, continua usando o console.
# Em produção, usa SMTP com as variáveis de ambiente.

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    if not all([EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD]):
        raise ImproperlyConfigured(
            'EMAIL_HOST, EMAIL_HOST_USER e EMAIL_HOST_PASSWORD são obrigatórias em produção.'
        )

DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='nao-responda@parabook.com.br'
)
CORS_ALLOW_CREDENTIALS = True

# URL publica do front-end React. Usada para montar os links enviados por email
# (ex: redefinicao de senha), que devem apontar para o parabook-web e nao para
# as telas legadas do Django.

FRONTEND_URL = config(
    'FRONTEND_URL',
    default='http://localhost:5173'
).rstrip('/')

# DRF Configuration

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'usuarios.api.authentication.CookieJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('API_THROTTLE_ANON', default='60/hour'),
        'user': config('API_THROTTLE_USER', default='1000/hour'),
        'auth': config('API_THROTTLE_AUTH', default='10/minute'),
        'password_reset': config('API_THROTTLE_PASSWORD_RESET', default='5/hour'),
        'upload': config('API_THROTTLE_UPLOAD', default='10/hour'),
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

JWT_ACCESS_COOKIE_NAME = config('JWT_ACCESS_COOKIE_NAME', default='parabook_access')
JWT_REFRESH_COOKIE_NAME = config('JWT_REFRESH_COOKIE_NAME', default='parabook_refresh')
JWT_COOKIE_SECURE = config('JWT_COOKIE_SECURE', default=not DEBUG, cast=bool)
JWT_COOKIE_SAMESITE = config('JWT_COOKIE_SAMESITE', default='Lax')
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SAMESITE = config('CSRF_COOKIE_SAMESITE', default='Lax')
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')

if (
    JWT_COOKIE_SAMESITE.lower() == 'none' and not JWT_COOKIE_SECURE
) or (
    CSRF_COOKIE_SAMESITE.lower() == 'none' and not CSRF_COOKIE_SECURE
):
    raise ImproperlyConfigured(
        'Cookies com SameSite=None devem usar Secure=True.'
    )

SPECTACULAR_SETTINGS = {
    'TITLE': 'ParaBook API',
    'DESCRIPTION': 'Documentação oficial das APIs do ParaBook (Fase 2)',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # 'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'],
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
}

# Configuração da Stripe com tratativa para variáveis ausentes

STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

LOG_LEVEL = config('LOG_LEVEL', default='INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {'()': 'config.logging.JsonFormatter'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'json'},
    },
    'root': {'handlers': ['console'], 'level': LOG_LEVEL},
}
