# Generated by Django 6.0.8 on 2026-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('SOLICITACAO', 'Solicitação de Publicação'), ('COMUNIDADE', 'Comunidade/Comentário'), ('ASSINATURA', 'Assinatura & Pagamentos'), ('SISTEMA', 'Sistema/Aviso')], default='SISTEMA', max_length=20, verbose_name='Tipo'),
        ),
    ]
